[package]
name = "db_fs"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[features]
inet_testing = []

[dependencies]
futures = "0.3.31"
sqlx = { version = "0.8.2", features = ["runtime-tokio"] }
tokio = { version = "1.40.0", features = ["full"] }
