default:
    just --list

_wait_for_container_start:
    @echo "waiting for database socket to open";
    @for i in {10..1}; do echo -n "$i "; sleep 1; done
    @echo

_prepare_prod_cont:
    podman run --detach --name dbfs --rm --env MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 -p "127.0.0.1:3306:3306" docker.io/mariadb:latest

_prepare_prod_db:
    #!/bin/bash
    user_creation="CREATE DATABASE \`dbfs\`; GRANT ALL PRIVILEGES ON \`dbfs\`.* TO 'dbfs'@'%' IDENTIFIED BY 'dbfs'; USE \`dbfs\`;"
    data_file=$(cat "./dbfs.sql")
    quit=$(echo -e "\nEXIT;")
    echo "$user_creation$data_file$quit" | podman exec -it dbfs mariadb


_prepare_testing_cont:
    podman run --detach --name dbfs_intest_db --rm --env MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 -p "127.0.0.1:3306:3306" docker.io/mariadb:latest

_prepare_testing_db:
    #!/bin/bash
    user_creation="CREATE DATABASE \`dbfs\`; GRANT ALL PRIVILEGES ON \`dbfs\`.* TO 'dbfs'@'%' IDENTIFIED BY 'dbfs'; USE \`dbfs\`;"
    setup_file=$(cat "./testing.sql")
    data_file=$(cat "./dbfs_test.sql")
    quit=$(echo -e "\nEXIT;")
    echo "$user_creation$setup_file$data_file$quit" | podman exec -it dbfs_intest_db mariadb


prod: _prepare_prod_cont _wait_for_container_start _prepare_prod_db
testing: _prepare_testing_cont _wait_for_container_start _prepare_testing_db
stop:
    -podman stop dbfs_intest_db
    -podman stop dbfs
